---
!include configs/base.yaml
---
dataset:
    name: cifar100
    num_classes: 100
    data_path: ./data
    lda_alpha: 0.1
    num_partitions: 500 # i.e. number of total clients
    val_ratio: 0.1
    val_global_sample_ratio:  1.0 # if < 1.0 a random subset of the global validation set will be used to score valid models in each bucket/tier


model:
    type: !bind:src.models.resnet_model.ResNetModel
        data_type: float32
        num_classes: !xref dataset.num_classes
        input_size: [1, 3, 32, 32]
        blocks: [4,4,4,4]
        stem: 64
        proj3x3: false

client: # settings for client when using fit() method and how much Ray allocates
    type: !bind:src.client.FedorASClient
        model_cfg: !xref model
        client_cfg:
            dataset: !xref dataset.name
            num_classes: !xref dataset.num_classes
            num_workers: 6
            batch_size: 64
            optim:
                type: !bind:torch.optim.SGD
                    lr: 0.1
                    momentum: 0.9
                    weight_decay: 0.0
            train_cfg: # parameterises the src.train.train calls
                gradclip: null
                perplexity: false
                epochs: 25
    ray_resources:
        num_cpus: !xref client.type.client_cfg.num_workers
        num_gpus: 0.5 # each client can take 50% of a GPU

finetuneclient:
    type: !bind:src.client.FedorASClient
        model_cfg: !xref model
        client_cfg:
            dataset: !xref dataset.name
            num_classes: !xref dataset.num_classes
            num_workers: 4
            batch_size: 32
            optim:
                type: !bind:torch.optim.SGD
                    lr: 0.01
                    momentum: 0.9
                    weight_decay: 0.0
            train_cfg: # parameterises the src.train.train calls
                gradclip: null
                perplexity: false
                epochs: 1
    ray_resources:
        num_cpus: !xref client.type.client_cfg.num_workers
        num_gpus: 0.5

clients_per_round: 10
num_rounds: 750
pdf_csum: 0.95
pdf_l_csum: 0.0
